package pl.jkap.sozzt.contract.domain;

enum ContractStepType {
    PRELIMINARY_PLAN,
    TERRAIN_VISION,
    PROJECT_PURPOSES_MAP_PREPARATION,
    ROUTE_PREPARATION,
    CONSENTS_COLLECTION,
    PREPARATION_OF_DOCUMENTATION
}
