package pl.jkap.sozzt.remark.domain;

public enum RemarkType {
    GENERAL_CONTRACT,
    PRELIMINARY_PLAN,
    TERRAIN_VISION,
    PROJECT_PURPOSES_MAP_PREPARATION,
    ROUTE_PREPARATION,
    LAND_EXTRACTS,
    CONSENTS_COLLECTION,
    PREPARATION_OF_DOCUMENTATION
}
