package pl.jkap.sozzt.filestorage.domain;

public enum FileType {
    CONTRACT_SCAN_FROM_TAURON,
    PRELIMINARY_MAP,
    PHOTO_FROM_PLACE_OF_THE_CONTRACT,
    PRELIMINARY_UPDATED_MAP,
    GEODETIC_MAP,
    PRIVATE_PLOT_OWNER_CONSENT_AGREEMENT,
    PUBLIC_OWNER_CONSENT_AGREEMENT,
    MAP_WITH_ROUTE,
    PDF_WITH_ROUTE_AND_DATA,
    COMPILED_DOCUMENT
}
